---
- name: RHEL Update
  hosts: all
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.package:
        name: "*"
        state: latest
    - name: List updated packages
      ansible.builtin.yum:
        list: updates