---
- name: RHEL Update
  hosts: all
  become: true
  tasks:
    - name: Update all packages
      ansible.builtin.package:
        name: "*"
        state: latest
    - name: List updated packages
      ansible.builtin.yum:
        list: updates
    # Display updated packages using debug module
    - name: Display updated packages using debug module
      ansible.builtin.debug:
        msg: "{{ _msg_ }}"